-- MySQL Script generated by MySQL Workbench
-- mar 09 oct 2018 11:56:52 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema script_tesina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema script_tesina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `script_tesina` DEFAULT CHARACTER SET utf8 ;
USE `script_tesina` ;

-- -----------------------------------------------------
-- Table `script_tesina`.`Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `script_tesina`.`Administradores` (
  `Administradores_Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellido` VARCHAR(100) NOT NULL,
  `Clave` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(100) NULL,
  PRIMARY KEY (`Administradores_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `script_tesina`.`Contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `script_tesina`.`Contactos` (
  `Contactos_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Contactos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `script_tesina`.`Salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `script_tesina`.`Salas` (
  `Salas_Id` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(150) NOT NULL,
  `Capacidad` INT NOT NULL,
  `Provincia` VARCHAR(100) NOT NULL,
  `CP` VARCHAR(15) NULL,
  `Ciudad` VARCHAR(100) NOT NULL,
  `Calle` VARCHAR(150) NOT NULL,
  `AlturaCalle` INT NOT NULL,
  `Contactos_id` INT NOT NULL,
  PRIMARY KEY (`Salas_Id`),
  INDEX `fk_Salas_Contactos1_idx` (`Contactos_id` ASC),
  CONSTRAINT `fk_Salas_Contactos1`
    FOREIGN KEY (`Contactos_id`)
    REFERENCES `script_tesina`.`Contactos` (`Contactos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `script_tesina`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `script_tesina`.`Eventos` (
  `Eventos_Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(300) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Costo` FLOAT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Administradores_Id` INT NOT NULL,
  `Salas_Id` INT NOT NULL,
  PRIMARY KEY (`Eventos_Id`),
  INDEX `fk_Eventos_Administradores_idx` (`Administradores_Id` ASC),
  INDEX `fk_Eventos_Salas1_idx` (`Salas_Id` ASC),
  CONSTRAINT `fk_Eventos_Administradores`
    FOREIGN KEY (`Administradores_Id`)
    REFERENCES `script_tesina`.`Administradores` (`Administradores_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eventos_Salas1`
    FOREIGN KEY (`Salas_Id`)
    REFERENCES `script_tesina`.`Salas` (`Salas_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `script_tesina`.`Entradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `script_tesina`.`Entradas` (
  `Entradas_Id` INT NOT NULL AUTO_INCREMENT,
  `Eventos_Id` INT NOT NULL,
  `Estado` ENUM('Libre', 'Vendida', 'Devuelta') NULL,
  INDEX `fk_Entradas_Eventos1_idx` (`Eventos_Id` ASC),
  PRIMARY KEY (`Entradas_Id`),
  CONSTRAINT `fk_Entradas_Eventos1`
    FOREIGN KEY (`Eventos_Id`)
    REFERENCES `script_tesina`.`Eventos` (`Eventos_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
