-- MySQL Script generated by MySQL Workbench
-- lun 26 nov 2018 16:22:03 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema script_tesina
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `script_tesina` ;

-- -----------------------------------------------------
-- Schema script_tesina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `script_tesina` DEFAULT CHARACTER SET utf8 ;
USE `script_tesina` ;

-- -----------------------------------------------------
-- Table `script_tesina`.`Administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `script_tesina`.`Administradores` ;

CREATE TABLE IF NOT EXISTS `script_tesina`.`Administradores` (
  `Administradores_Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellido` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `Clave` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(100) NULL,
  PRIMARY KEY (`Administradores_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `script_tesina`.`Contactos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `script_tesina`.`Contactos` ;

CREATE TABLE IF NOT EXISTS `script_tesina`.`Contactos` (
  `Contactos_Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(100) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Contactos_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `script_tesina`.`Salas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `script_tesina`.`Salas` ;

CREATE TABLE IF NOT EXISTS `script_tesina`.`Salas` (
  `Salas_Id` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(150) NOT NULL,
  `Capacidad` INT NOT NULL,
  `Provincia` VARCHAR(100) NOT NULL,
  `CP` VARCHAR(15) NULL,
  `Ciudad` VARCHAR(100) NOT NULL,
  `Calle` VARCHAR(150) NOT NULL,
  `AlturaCalle` INT NOT NULL,
  `Contactos_Id` INT NOT NULL,
  PRIMARY KEY (`Salas_Id`),
  INDEX `fk_Salas_Contactos1_idx` (`Contactos_Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `script_tesina`.`Eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `script_tesina`.`Eventos` ;

CREATE TABLE IF NOT EXISTS `script_tesina`.`Eventos` (
  `Eventos_Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(300) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Costo` FLOAT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Administradores_Id` INT NOT NULL,
  `Salas_Id` INT NOT NULL,
  PRIMARY KEY (`Eventos_Id`),
  INDEX `fk_Eventos_Administradores_idx` (`Administradores_Id` ASC),
  INDEX `fk_Eventos_Salas1_idx` (`Salas_Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `script_tesina`.`Entradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `script_tesina`.`Entradas` ;

CREATE TABLE IF NOT EXISTS `script_tesina`.`Entradas` (
  `Entradas_Id` INT NOT NULL AUTO_INCREMENT,
  `Eventos_Id` INT NOT NULL,
  `Estado` ENUM('Libre', 'Impresa', 'Vendida', 'Ingresado', 'Devuelta') NOT NULL,
  `Nro` INT NOT NULL,
  `DNI` VARCHAR(45) NULL,
  `NombreComprador` VARCHAR(255) NULL,
  INDEX `fk_Entradas_Eventos1_idx` (`Eventos_Id` ASC),
  PRIMARY KEY (`Entradas_Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `script_tesina`.`Administradores`
-- -----------------------------------------------------
START TRANSACTION;
USE `script_tesina`;
INSERT INTO `script_tesina`.`Administradores` (`Administradores_Id`, `Nombre`, `Apellido`, `Clave`, `Email`, `Telefono`) VALUES (1, 'Juan', 'Gomez', '1234', 'juangomez@gmail.com', '02944 123455');
INSERT INTO `script_tesina`.`Administradores` (`Administradores_Id`, `Nombre`, `Apellido`, `Clave`, `Email`, `Telefono`) VALUES (2, 'Julian', 'Fernandez', '4321', 'julian@gmail.com', '02944 345643');

COMMIT;


-- -----------------------------------------------------
-- Data for table `script_tesina`.`Contactos`
-- -----------------------------------------------------
START TRANSACTION;
USE `script_tesina`;
INSERT INTO `script_tesina`.`Contactos` (`Contactos_Id`, `Nombre`, `Apellido`, `Email`, `Telefono`, `Clave`) VALUES (1, 'Pablo', 'Vazquez', 'pablo@gmail.com', '02944 343434', '1234');
INSERT INTO `script_tesina`.`Contactos` (`Contactos_Id`, `Nombre`, `Apellido`, `Email`, `Telefono`, `Clave`) VALUES (2, 'Fernando', 'Patirri', 'fernando@yahoo.com', '02333 676767', '4321');
INSERT INTO `script_tesina`.`Contactos` (`Contactos_Id`, `Nombre`, `Apellido`, `Email`, `Telefono`, `Clave`) VALUES (3, 'Julian', 'Gomez', 'juli@mail.com', '02944 3455787', 'abcd');

COMMIT;


-- -----------------------------------------------------
-- Data for table `script_tesina`.`Salas`
-- -----------------------------------------------------
START TRANSACTION;
USE `script_tesina`;
INSERT INTO `script_tesina`.`Salas` (`Salas_Id`, `Descripcion`, `Capacidad`, `Provincia`, `CP`, `Ciudad`, `Calle`, `AlturaCalle`, `Contactos_Id`) VALUES (1, 'Bolichon', 200, 'Rio Negro', '8400', 'San Carlos de Bariloche', 'Mitre', 500, 1);
INSERT INTO `script_tesina`.`Salas` (`Salas_Id`, `Descripcion`, `Capacidad`, `Provincia`, `CP`, `Ciudad`, `Calle`, `AlturaCalle`, `Contactos_Id`) VALUES (2, 'La pulperia', 150, 'Rio Negro', '8500', 'Viedma', 'Onelli ', 700, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `script_tesina`.`Eventos`
-- -----------------------------------------------------
START TRANSACTION;
USE `script_tesina`;
INSERT INTO `script_tesina`.`Eventos` (`Eventos_Id`, `Nombre`, `Descripcion`, `Costo`, `Fecha`, `Hora`, `Administradores_Id`, `Salas_Id`) VALUES (1, 'Almafuerte', 'Recital de Almafuerte, con sus exitos de ahora y siempre.  Metal puro y nacional.', 450, '2018-11-22', '23:00', 1, 1);
INSERT INTO `script_tesina`.`Eventos` (`Eventos_Id`, `Nombre`, `Descripcion`, `Costo`, `Fecha`, `Hora`, `Administradores_Id`, `Salas_Id`) VALUES (2, 'Catupecu Machu', 'Recital de la banda mas loca del mundo, con toda la potencia y garra', 500, '2018-12-25', '23:30', 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `script_tesina`.`Entradas`
-- -----------------------------------------------------
START TRANSACTION;
USE `script_tesina`;
INSERT INTO `script_tesina`.`Entradas` (`Entradas_Id`, `Eventos_Id`, `Estado`, `Nro`, `DNI`, `NombreComprador`) VALUES (1, 1, 'Libre', 1, NULL, NULL);
INSERT INTO `script_tesina`.`Entradas` (`Entradas_Id`, `Eventos_Id`, `Estado`, `Nro`, `DNI`, `NombreComprador`) VALUES (2, 1, 'Libre', 2, NULL, NULL);

COMMIT;

